variables:
  projectDirectory: ''

trigger:
- main

stages:
- stage: AndroidStage
  dependsOn: []
  displayName: Android
  jobs:
  - job: Android
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '$(projectDirectory)'
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksignerKeystoreFile: 'key.jks'
        apksignerKeystorePassword: $(keyStorePassword)
        apksignerKeystoreAlias: $(keyStoreAlias)
        apksignerKeyPassword: $(keyPassword)
        zipalign: false
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: "Publish AAB file"
      inputs:
        PathtoPublish: '$(build.artifactStagingDirectory)'
        ArtifactName: 'AAB'
        publishLocation: 'Container'

