name: rsi
description: This is RSI mobile application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  percent_indicator: ^4.2.2
  dio: ^4.0.4
  json_annotation: ^4.4.0
  provider: ^6.0.2
  firebase_auth: ^3.3.14
  google_sign_in: ^5.4.0
  flutter_facebook_auth: ^4.1.1
  firebase_core: ^1.12.0
  sizer: ^2.0.15
  shared_preferences: ^2.0.13
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  pull_to_refresh: ^2.0.0
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  flutter_html: ^2.2.1
  webview_flutter: ^2.8.0
  shimmer: ^2.0.0
  flutter_cached_pdfview: ^0.4.1
  tuple: ^2.0.0
  pattern_formatter: ^2.0.0
  flutter_svg: ^0.23.0+1
  flutter_material_pickers: ^3.1.4+1
  quiver: ^3.1.0
  fl_chart: ^0.55.2
  url_launcher: ^6.1.5
  grouped_list: ^5.1.2
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.1.0
  collection: ^1.16.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Public Sans
      fonts:
        - asset: assets/fonts/PublicSans-Bold.ttf
        - asset: assets/fonts/PublicSans-Light.ttf
        - asset: assets/fonts/PublicSans-Medium.ttf
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-Thin.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
